# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0bc8f09c73540101c7b4c4f41f93ffd67c852a4b46985d919cf126fc9cf511690c4af13f748137a3837f7543b146cd8404afa77deee16d154c26ff7d67ec68f

test:
  secret_key_base: 8ce43d53803be50f98aa60261df132f5f575d890e57c5a0ab04f14b4a80064ffde8c2e44dc3887d13bd197f14f660024d6f8a9abd61dff771e6ab423ed403333

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
